### ISSUE TITLE
Promod Source Code

### ISSUE THREAD

**Issue by jNizM** [promod/promod.github.io#1]
Hey Ingram,
first thanks for your great work on PromodLive.
It would be nice to see the promod source code here on github too.
So next to the official Promod release we got something for public server developer and people who can fix (eventual) bugs, increase the performance or add new interesting features.

greets

**Comment by Ingramz** [comment]
Hi, all I can say is that we (Trivve and I) are currently evaluating this. There are things that need to be figured out and taken care of before we can publish the source code for it. Unfortunately I am rather busy at the moment, so I cannot promise you a date.

**Comment by Kingwolf123** [comment]
Hey Ingramz,

Any Update on this?

**Comment by Ingramz** [comment]
@Kingwolf123 we're terribly sorry it took this long, there were some issues that needed to be solved and this took some time to plan between me and Trivve. For Call of Duty 4's 10th birthday, we have released the source code: https://github.com/promod/promod4

If you have any issues, you can create an issue there and we'll help you out.
